name: Release

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Build Linux binary
        run: GOOS=linux GOARCH=amd64 go build -o valfs-linux-amd64

      # Build both Mac binaries
      - name: Build Mac binaries
        run: |
          GOOS=darwin GOARCH=amd64 go build -o valfs-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -o valfs-darwin-arm64

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload Linux Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./valfs-linux-amd64
          asset_name: valfs-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload Mac Intel Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./valfs-darwin-amd64
          asset_name: valfs-darwin-amd64
          asset_content_type: application/octet-stream

      - name: Upload Mac Apple Silicon Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./valfs-darwin-arm64
          asset_name: valfs-darwin-arm64
          asset_content_type: application/octet-stream
